Repository Team-Senior-Link/senior-link, pull requests merged in 2024-06, with the labels that each got.

#17 Feat: 채팅 기능 구현
  build.gradle
  src/main/java/com/cteam/seniorlink/chat/ChatController.java
  src/main/java/com/cteam/seniorlink/chat/ChatService.java
  src/main/java/com/cteam/seniorlink/chat/message/ChatMessageDto.java
  src/main/java/com/cteam/seniorlink/chat/message/ChatMessageEntity.java
  src/main/java/com/cteam/seniorlink/chat/message/ChatMessageRepository.java
  src/main/java/com/cteam/seniorlink/chat/room/ChatRoomDto.java
  src/main/java/com/cteam/seniorlink/chat/room/ChatRoomEntity.java
  src/main/java/com/cteam/seniorlink/chat/room/ChatRoomRepository.java
  src/main/java/com/cteam/seniorlink/config/SecurityConfig.java
  src/main/java/com/cteam/seniorlink/config/StompWebSocketConfig.java
  src/main/resources/templates/chat/list.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/service/edit.html
  src/main/resources/templates/user/mypage.html
Labels: feat

#19 Fix: userdetails 에러 해결
  src/main/java/com/cteam/seniorlink/user/UserSecurityService.java
Labels: fix

#20 Feat: 프로필 사진 등록 및 출력
  senior-link/src/main/resources/static/profile/1717651295649.jpeg
  senior-link/src/main/resources/static/profile/1717651612496.jpeg
  senior-link/src/main/resources/static/profile/81fab2e0ba2579e391c29b2da66ace24.jpg
  senior-link/src/main/resources/static/profile/GM3y52DaAAAH3dE.jpeg
  src/main/java/com/cteam/seniorlink/config/SecurityConfig.java
  src/main/java/com/cteam/seniorlink/user/FileController.java
  src/main/java/com/cteam/seniorlink/user/UserController.java
  src/main/java/com/cteam/seniorlink/user/UserCreateRequest.java
  src/main/java/com/cteam/seniorlink/user/UserEditRequest.java
  src/main/java/com/cteam/seniorlink/user/UserEntity.java
  src/main/java/com/cteam/seniorlink/user/UserService.java
  src/main/resources/static/profile/default_profile_image.jpg
  src/main/resources/templates/user/mypage.html
Labels: feat

#21 Refactor: security config migration
  src/main/java/com/cteam/seniorlink/config/SecurityConfig.java
Labels: refactor

#27 오류 수정
  src/main/java/com/cteam/seniorlink/certification/CertificationController.java
  src/main/java/com/cteam/seniorlink/certification/ErrorController.java
  src/main/java/com/cteam/seniorlink/config/SecurityConfig.java
  src/main/java/com/cteam/seniorlink/schedule/ScheduleController.java
  src/main/java/com/cteam/seniorlink/user/UserController.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/certification/access-denied.html
  src/main/resources/templates/certification/add.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/nav.html
  src/main/resources/templates/schedule/schedule.html
  src/main/resources/templates/service/add.html
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/videoBoard/edit.html
  src/main/resources/templates/videoBoard/list.html
Labels: fix
